[package]
name = "sleigh2c"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sleigh-rs = "0.1.5"
sleigh2rust = "0.1.6"
